### ISSUE TITLE
Support for various database technologies

### ISSUE THREAD

**Issue by 3keyroman** [Keyfactor/ejbca-ce-helm-meetup#1]
Currently it is possible to install helm chart only with the MariaDB and specific configuration, for example database name must be always `ejbca` otherwise it does not work.

In the [EJBCA deployment template](https://github.com/Keyfactor/ejbca-ce-helm-meetup/blob/master/charts/ejbca-ce/templates/ejbca/deployment.yaml) is an init container named `ca-cert-locator` that fails if the database is not named `ejbca`.

Anyway, the support for other database technologies should be extended and improved.
Configuration properties should be technology-agnostic, for example:
```yaml
database:
  localDeployment:
    # If deployDatabase is enabled, a pod is deployed with a ClusterIP service.
    deployDatabase: false
    # A secret is also created containing the credentials
    username: ejbca
    password: ejbca
    passwordRoot: foo123
    image:
      repository: mariadb
      pullPolicy: IfNotPresent
      tag: "10.5"
  # If deployDatabase is true, endpoint is used as the name label used by a database deployment and associated service.

  # Database secret name is required to securely retrieve database credentials. Used regardless of localDeployment state
  secretName: ejbca-database-credentials

  # database technology, for example mariadb, postgresql
  type: "postgresql"
  host: "database-svc"
  port: 5432
  name: "ejbca"
  username: "ejbcauser"
  password: "your-strong-password"
  # optional to add specific properties to database connection string
  properties: ""
```

Link #2
